###
GET http://localhost:8080/products/2
###
POST http://localhost:8080/products
Content-Type: application/json

{
  "productId": 1,
  "name": "Samsung S24",
  "description": "Flagship Samsung smartphone with powerful features.",
  "price": 899.99,
  "category": "Electronics",
  "subCategory": "Smartphones",
  "brand": "Samsung",
  "specifications": [{
    "key": "value",
    "value": "100"
  }],
  "tags": [
    "phone"
  ]
}
