spring:
  application:
      name: product-catalog
  jackson:
    default-property-inclusion: non_empty

logging:
  level:
    # Show SQL statements
    org.jooq.tools.LoggerListener: DEBUG
    # Show Requests
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.zalando.logbook: TRACE

logbook:
  filter:
    enabled: true